[project]
name = "water"
version = "1.0.0"
description = "This is a webserver for Case 5."
dependencies =[
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
